# Generated by Django 4.2.6 on 2023-11-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('scu', models.PositiveSmallIntegerField()),
                ('sem', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('major_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.major')),
            ],
        ),
        migrations.CreateModel(
            name='Major_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.course')),
                ('major_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.major')),
            ],
        ),
    ]
