# Generated by Django 4.2.6 on 2023-12-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Major_Course',
        ),
    ]
