# Generated by Django 4.2.6 on 2023-12-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_delete_major_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCU',
            fields=[
                ('scu', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('MaxAbs', models.PositiveSmallIntegerField()),
                ('TotalSec', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
