# Generated by Django 4.2.6 on 2023-12-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_scu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='scu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.scu'),
        ),
    ]
