# Generated by Django 4.2.6 on 2023-11-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_course_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='scu',
            field=models.PositiveSmallIntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
