# Generated by Django 4.2.6 on 2023-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_course_course_id_alter_course_scu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
