# Generated by Django 4.2.6 on 2023-11-04 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sem',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.major'),
        ),
    ]
