# Generated by Django 4.2.6 on 2023-11-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_course_sem_alter_student_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='scu',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Major_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.major')),
            ],
        ),
    ]
