# Generated by Django 4.2.6 on 2023-11-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_course_scu_major_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major_course',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.course'),
        ),
        migrations.AlterField(
            model_name='major_course',
            name='major_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.major'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(to='students.course'),
        ),
    ]
