# Generated by Django 4.2.6 on 2023-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_teacher_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
