# Generated by Django 4.2.6 on 2023-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_remove_teacher_courses_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='major',
            field=models.ManyToManyField(to='students.major'),
        ),
    ]
