# Generated by Django 4.2.6 on 2023-11-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_teacher_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='courses',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='major',
        ),
    ]
