# Generated by Django 4.2.6 on 2023-11-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_rename_courses_teacher_course_remove_teacher_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='course',
            new_name='courses',
        ),
    ]
