# Generated by Django 4.2.6 on 2023-11-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_rename_course_teacher_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
