# Generated by Django 4.2.6 on 2023-11-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banner',
        ),
    ]
